on:
  push:
    branches:
      - KDE
  pull_request:
    branches:
      - KDE
  release:
    types:
      - published
  schedule:
  - cron: "0 0 * * 5"
jobs:
  build_iso:
    name: Build ISO
    runs-on: self-hosted
    timeout-minutes: 10080
    steps:
      - name: clean old files
        run: |
          sudo rm -rf squashfs stat *.iso *.md5
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: install deps
        run: |
          sudo apt update
          sudo apt -y install m4 wget xz-utils git rsync make squashfs-tools asciidoc
      - name: build iso
        run: |
          sudo bash -x ./build.sh
      - name: create md5sum
        run: |
          for f in *.iso; do [ -e "$f" ] && md5sum "$f" > "${f}.md5"; done
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ISO
          path: ./*.iso*
      - name: upload release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          with: ./*.iso*
